### ISSUE TITLE
Multiple exec() don't execute

### ISSUE THREAD

**Issue by rwieruch** [rwieruch/github-webhook-automatic-blog-deployment#2]
If this webhook API endpoint receives multiple requests in a row, it seems like the `exec()` command isn't executing all `webhook.sh` files properly. Should I use something else than `exec()`, maybe `spawn()`, to make it work for multiple incoming requests?

https://github.com/rwieruch/github-webhook-automatic-blog-deployment/blob/cee92dd55c20bd8763366b9b1f86550c50a75292/src/index.js#L66

**Comment by mrm8488** [comment]
Have you tried to do it in **background**?
```js
exec((`cd ${entry} && bash webhook.sh`) &)
```
